### ISSUE TITLE
NinjectFileLessServiceHostFactory sample for WcfLibrary is not working

### ISSUE THREAD

**Issue by jzinedine** [ninject/Ninject.Extensions.Wcf#22]
Even though I've downloaded all pre packages from nuget, and solution get compiled successfully but NinjectFileLessServiceHostFactory never get called upon running the project and I'll get this error message: (service type provided could not be loaded as a service because it does not have a default (parameter-less) constructor)

``` C#
System.InvalidOperationException: The service type provided could not be loaded as a service because it does not have a default (parameter-less) constructor. To fix the problem, add a default constructor to the type, or pass an instance of the type to the host.
   at System.ServiceModel.Dispatcher.InstanceBehavior..ctor(DispatchRuntime dispatch, ImmutableDispatchRuntime immutableRuntime)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime..ctor(DispatchRuntime dispatch)
   at System.ServiceModel.Dispatcher.DispatchRuntime.GetRuntimeCore()
   at System.ServiceModel.Dispatcher.ChannelDispatcher.OnOpened()
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.ServiceHostBase.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at Microsoft.Tools.SvcHost.ServiceHostHelper.OpenService(ServiceInfo info)
```

**Comment by tuncatunc** [comment]
Is there any workaround to make it work?

**Comment by jvsanchez28** [comment]
I got the same error, is there a way to fix this?

**Comment by scott-xu** [comment]
Did you regiter route? Did you use configuration-based activation?

**Comment by scott-xu** [comment]
If your address is *.svc, please use svc file or configuration-based activation. Registering route in RouteTable is for non-*.svc (mostly for extensionless) URL.
